### ISSUE TITLE
Could not connect to the myo motor: I/O error

### ISSUE THREAD

**Issue by compiaffe** [Roboy/myo_blink#6]
When roslaunching the project I get a
`Could not connect to the myo motor: I/O error`

What am I doing wrong?

**Comment by compiaffe** [comment]
You most likely have not unloaded the standard ftdi driver correctly. This should be done automatically by the udev rules you installed. However, you can do this manually on the (host) machine. 

` sudo rmmod ftdi_sio
`

**Comment by missxa** [comment]
```
[ 1340.941119] ftdi_sio 1-9:1.0: FTDI USB Serial Device converter detected
[ 1340.941188] usb 1-9: Detected FT232H
[ 1340.941452] usb 1-9: FTDI USB Serial Device converter now attached to ttyUSB0
[ 1340.949497] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[ 1340.949543] ftdi_sio 1-9:1.0: device disconnected
```
driver is unloaded but I still get I/O error. any idea why?

**Comment by compiaffe** [comment]
First of all check if you have read/write access the ftdi device before unloading the 
ftdi_sio (with `rmmod ftdi_sio`):

`cat /dev/ttyUSB0
`
or 

`ls -alh /dev/ttyUSB*
`

You might need to give the user r/w access, by i.e. adding them and your account to a common group with r/w acces such as 'dialout'. (see here: [AskUbuntu non-default user access to serial device](http://askubuntu.com/questions/112568/how-do-i-allow-a-non-default-user-to-use-serial-device-ttyusb0))

**Comment by missxa** [comment]
The problem was our udev rule. The final udev rule that works is:
```
SUBSYSTEMS=="usb", ATTR{manufacturer}=="FTDI", ATTR{idVendor}=="0403", ATTR{idProduct}=="6014", ATTR{product}=="UM232H", ATTR{serial}=="FTY4PDYV", RUN+="/bin/sh -c 'echo -n %k:1.0 > /sys/bus/usb/drivers/ftdi_sio/unbind'"
```
